services:
  owncloud:
    image: owncloud/server:latest
    container_name: owncloud
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
      - redis
    environment:
      - OWNCLOUD_DOMAIN=dominio:8080
      - OWNCLOUD_TRUSTED_DOMAINS=127.0.0.1,dominio,localhost
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=db
      - OWNCLOUD_ADMIN_USERNAME=jobs
      - OWNCLOUD_ADMIN_PASSWORD=apple
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    volumes:
      - ./files:/mnt/data
    networks:
      - owncloud_network
    deploy:
      resources:
        limits:
          memory: 768M  # Limite de memória
          cpus: '0.70'  # Limite de CPU (50% de um núcleo)

  db:
    image: mariadb:latest
    container_name: own_mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=owncloud
      - MYSQL_ROOT_PASSWORD=owncloud
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
    command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M"]
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - owncloud_network

  redis:
    image: redis:latest
    container_name: own_redis
    restart: always
    command: ["--databases", "1"]
    volumes:
      - ./redis:/data
    networks:
      - owncloud_network
  
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - owncloud_network
    depends_on:
      - owncloud

networks:
  owncloud_network:
    driver: bridge
